//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorageCalc.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StorageCalc.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. 4 Platten und gerade Anzahl notwendig.
        /// </summary>
        public static string AtLeastFourPlatesAndEvenNumber {
            get {
                return ResourceManager.GetString("AtLeastFourPlatesAndEvenNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. 4 Platten notwendig.
        /// </summary>
        public static string AtLeastFourPlatesRequired {
            get {
                return ResourceManager.GetString("AtLeastFourPlatesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. 3 Platten notwendig.
        /// </summary>
        public static string AtLeastThreePlatesRequired {
            get {
                return ResourceManager.GetString("AtLeastThreePlatesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berechnen.
        /// </summary>
        public static string CalculateButton {
            get {
                return ResourceManager.GetString("CalculateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genau 2 Platten benötigt.
        /// </summary>
        public static string ExactlyTwoPlatesAreRequired {
            get {
                return ResourceManager.GetString("ExactlyTwoPlatesAreRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehlertoleranz:.
        /// </summary>
        public static string FaultToleranceTextBlock {
            get {
                return ResourceManager.GetString("FaultToleranceTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. 1 Platte.
        /// </summary>
        public static string MinOneDisk {
            get {
                return ResourceManager.GetString("MinOneDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to keine.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl Platten:.
        /// </summary>
        public static string NumberOfPlatesTextBlock {
            get {
                return ResourceManager.GetString("NumberOfPlatesTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Platte.
        /// </summary>
        public static string OneDisk {
            get {
                return ResourceManager.GetString("OneDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overflow, bitte kleinere Zahlen eingeben.
        /// </summary>
        public static string PleaseEnterSmallerNumbers {
            get {
                return ResourceManager.GetString("PleaseEnterSmallerNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eingabe prüfen, bitte nur Zahlen eingeben.
        /// </summary>
        public static string PleaseOnlyEnterNumber {
            get {
                return ResourceManager.GetString("PleaseOnlyEnterNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grösse einer Platte in TB:.
        /// </summary>
        public static string SizeOfDiskInTBTextBlock {
            get {
                return ResourceManager.GetString("SizeOfDiskInTBTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da ging was schief:.
        /// </summary>
        public static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Platten.
        /// </summary>
        public static string TwoDisks {
            get {
                return ResourceManager.GetString("TwoDisks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutzbarer Platz:.
        /// </summary>
        public static string UseableSpaceTextBlock {
            get {
                return ResourceManager.GetString("UseableSpaceTextBlock", resourceCulture);
            }
        }
    }
}